namespace :denial_codes do
  desc "Update denial codes from the given list"
  task :create => :environment do
    denial_codes = [
      { denial_code: "AUTH-001", description: "Prior approval is required and was not obtained" },
      { denial_code: "AUTH-003", description: "PriorAuthorizationNumber is invalid" },
      { denial_code: "AUTH-004", description: "Service(s) is (are) performed outside authorization validity date" },
      { denial_code: "AUTH-005", description: "Claim information is inconsistent with pre-certified/authorized services" },
      { denial_code: "BENX-002", description: "Benefit maximum for this time period or occurrence has been reached" },
      { denial_code: "BENX-005", description: "Annual limit/sublimit amount exceeded" },
      { denial_code: "CLAI-007", description: "Claim is a work-related injury/illness and thus the liability of the employer" },
      { denial_code: "CLAI-008", description: "Claim overlaps inpatient stay. Resubmit only those services rendered outside the inpatient stay" },
      { denial_code: "CLAI-009", description: "Date of birth follows the date of service" },
      { denial_code: "CLAI-010", description: "Date of death precedes the date of service" },
      { denial_code: "CLAI-011", description: "Inpatient admission spans multiple rate periods. Resubmit separate claims" },
      { denial_code: "CLAI-012", description: "Submission not compliant with contractual agreement between provider & payer" },
      { denial_code: "CLAI-014", description: "Claim not compliant with Resubmission type (used only for resubmissions)" },
      { denial_code: "CODE-010", description: "Activity/diagnosis inconsistent with clinician specialty" },
      { denial_code: "CODE-012", description: "Encounter type inconsistent with service(s) / diagnosis" },
      { denial_code: "CODE-013", description: "Invalid principal diagnosis" },
      { denial_code: "CODE-014", description: "Activity/diagnosis is inconsistent with the patient's age/gender" },
      { denial_code: "CODE-015", description: "Activity/diagnosis is inconsistent with the provider type" },
      { denial_code: "COPY-001", description: "Deductible/co-pay not collected from member" },
      { denial_code: "DUPL-001", description: "Claim is a duplicate based on service codes and dates" },
      { denial_code: "DUPL-002", description: "Payment already made for same/similar service within set time frame" },
      { denial_code: "ELIG-001", description: "Patient is not a covered member" },
      { denial_code: "ELIG-005", description: "Services performed after the last date of coverage" },
      { denial_code: "ELIG-006", description: "Services performed prior to the effective date of coverage" },
      { denial_code: "ELIG-007", description: "Services performed by a non-network provider" },
      { denial_code: "MNEC-003", description: "Service is not clinically indicated based on good clinical practice" },
      { denial_code: "MNEC-004", description: "Service is not clinically indicated based on good clinical practice, without additional supporting diagnoses/activities" },
      { denial_code: "MNEC-005", description: "Service/supply may be appropriate, but too frequent" },
      { denial_code: "MNEC-006", description: "Alternative service should have been utilized" },
      { denial_code: "NCOV-001", description: "Diagnosis(es) is (are) not covered" },
      { denial_code: "NCOV-002", description: "Pre-existing conditions are not covered" },
      { denial_code: "NCOV-003", description: "Service(s) is (are) not covered" },
      { denial_code: "NCOV-025", description: "Service(s) is (are) not performed (used after audit)" },
      { denial_code: "PRCE-001", description: "Calculation discrepancy" },
      { denial_code: "PRCE-002", description: "Payment is included in the allowance for another service" },
      { denial_code: "PRCE-003", description: "Recovery of Payment" },
      { denial_code: "PRCE-006", description: "Consultation within free follow up period" },
      { denial_code: "PRCE-007", description: "Service has no contract price" },
      { denial_code: "PRCE-008", description: "Multiple procedure payment rules incorrectly applied" },
      { denial_code: "PRCE-009", description: "Charges inconsistent with clinician specialty" },
      { denial_code: "PRCE-010", description: "Use bundled code" },
      { denial_code: "TIME-001", description: "Time limit for submission has expired" },
      { denial_code: "TIME-002", description: "Requested additional information was not received or was not received within time limit" },
      { denial_code: "TIME-003", description: "Appeal procedures not followed or time limits not met" },
      { denial_code: "AUTH-006", description: "Alert drug - drug interaction or drug is contra-indicated" },
      { denial_code: "AUTH-007", description: "Drug duplicate therapy" },
      { denial_code: "AUTH-008", description: "Inappropriate drug dose" },
      { denial_code: "AUTH-009", description: "Prescription out of date" },
      { denial_code: "AUTH-010", description: "Authorization request overlaps or is within the period of another paid claim or approved authorization" },
      { denial_code: "AUTH-011", description: "Waiting period on pre-existing / specific conditions" },
      { denial_code: "CLAI-017", description: "Services not available on direct billing" },
      { denial_code: "CLAI-018", description: "Claims Recalled By Provider" },
      { denial_code: "PRCE-011", description: "Discount discrepancy" },
      { denial_code: "SURC-001", description: "Severe drug - drug interaction" },
      { denial_code: "SURC-002", description: "Severe drug - age contraindication" },
      { denial_code: "SURC-003", description: "Severe drug - gender contraindication" },
      { denial_code: "SURC-004", description: "Severe drug - diaganosis contraindication" },
      { denial_code: "SURC-005", description: "Severe procedure/service - diagnosis contraindication" },
      { denial_code: "SURC-006", description: "Severe procedure/service - drug contraindication" },
      { denial_code: "SURC-007", description: "Severe procedure/service - procedure contraindication" },
      { denial_code: "SURC-008", description: "Serious safety issue with drug dose" },
      { denial_code: "WRNG-001", description: "Wrong submission, receiver is not responsible for the payer within this transaction submission" },
      { denial_code: "CLAI-019", description: "Incorrect IR-DRG code" },
      { denial_code: "CLAI-020", description: "Missing IR-DRG code" },
      { denial_code: "AUTH-012", description: "Request for information" },
      { denial_code: "AUTH-002", description: "Services performed are inconsistent with authorized or approved services" },
      { denial_code: "AUTH-013", description: "Missing eRx Reference number" },
      { denial_code: "BENX-001", description: "Service / Medication is above AED threshold" },
      { denial_code: "CLAI-013", description: "Missing an Observation (Dental Tooth #)" },
      { denial_code: "CLAI-021", description: "Incorrect DRG payment parameter" },
      { denial_code: "CLAI-022", description: "Missing DRG payment parameter" },
      { denial_code: "CODE-001", description: "Missing, incomplete or invalid principal diagnosis" },
      { denial_code: "CODE-002", description: "Missing, incomplete or invalid service code" },
      { denial_code: "CODE-006", description: "Diagnosis is inconsistent with the procedure" },
      { denial_code: "CODE-014", description: "Activity/diagnosis is inconsistent with the patient's age/gender" },
      { denial_code: "CODE-016", description: "Activity/diagnosis inconsistent with Service" },
      { denial_code: "MNEC-007", description: "Service is not clinically indicated based on good clinical practice, without additional supporting documentation" },
      { denial_code: "NCOV-009", description: "Dental treatments are not covered" },
      { denial_code: "NCOV-010", description: "Elective procedure is not covered" },
      { denial_code: "NCOV-012", description: "Eye exams and treatments are not covered" },
      { denial_code: "NCOV-014", description: "Hearing services are not covered" },
      { denial_code: "NCOV-018", description: "Immunizations are not covered" },
      { denial_code: "NCOV-019", description: "Preventative care is not covered" },
      { denial_code: "NCOV-020", description: "Services resulting from attempted suicide or self-infliction are not covered" },
      { denial_code: "NCOV-021", description: "Vaccinations are not covered" },
      { denial_code: "NCOV-024", description: "Chronic Condition Service(s) is (are) not covered" },
      { denial_code: "NCOV-027", description: "Non Coverage of certain medication as per policy" },
      { denial_code: "AUTH-014", description: "Medication has been added to a prior request that is not in line with Pharmacist Edit Restrictions" },
      { denial_code: "PRCE-012", description: "Recovery of Payment – DHIC Authorized" },
      { denial_code: "DRG-001", description: "Incorrect DRG code" },
      { denial_code: "DRG-002", description: "Missing DRG code" },
      { denial_code: "DRG-003", description: "Incorrect Billing Regime" },
      { denial_code: "DRG-004", description: "Missing Activities" },
      { denial_code: "COPY-002", description: "Incorrect Patient Share" },
      { denial_code: "COPY-003", description: "Missing Patient Share" },
      { denial_code: "DRG-005", description: "Missing Observation (ActivityCost and/or File Attachment)" },
      { denial_code: "BSMA-001", description: "Member not covered under Basmah" },
      { denial_code: "BSMA-002", description: "Claims is not eligible under Basmah Fund" },
      { denial_code: "BSMA-003", description: "Prior approval is required but not taken (Basmah)" },
      { denial_code: "CLAI-023", description: "Submission not compliant with contractual agreement between non-network physician & payer" },
      { denial_code: "ELIG-008", description: "Services performed by a non-network physician" }
    ]


    denial_codes.each do |code|
      record = Denialcodelist.find_or_create_by(denial_code: code[:denial_code], description: code[:description])
      puts "Updated Denial Code: #{record.inspect}"
    end
  end
end
